### ISSUE TITLE
Comments section missing from book review article

### ISSUE THREAD

**Issue by evolvemind** [jazzsequence/book-review-library#61]
I added your Book Reviews plug-in to my site at https://albuquirky.net. The checkbox to allow commenting is selected but the comment area does not display on each book review page. My plugins follow:

1&1 WP Wizard   Deactivate
Akismet Anti-Spam   Deactivate
All In One SEO Pack   Deactivate
Book Review Library   Deactivate
BuddyPress   Activate
Compact Audio Player   Deactivate
Divi Builder   Deactivate
Google XML Sitemaps   Deactivate
Head, Footer and Post   Injections   Deactivate
Jetpack by WordPress.com   Deactivate
TinyMCE Advanced   Deactivate
UpdraftPlus -   Backup/Restore   Deactivate
WP File Download   Deactivate
WP File Download Addon   Deactivate

My theme is Extra 2.11.1 from Elegant Themes.

**Comment by jazzsequence** [comment]
Hey! 👋 
So I had a chance to play with this a bit today and was reminded of a weird quirk of WordPress which explains your issue.

Comments, though a general setting, are specific to individual posts (and by "post", I'm using the term loosely as it applies to all things within WordPress including pages and, in this case, book reviews). For instance, you can turn comments on for Pages in general, and then everyone can comment on your pages. If you then turn off commenting on pages, people won't be able to comment on any _new_ pages you create, but all the old pages that had comments on them before will still allow people to comment on them.

What does this mean for you? Well, primarily it means that toggling comments for book reviews should work -- for all _new_ book reviews. But previous reviews that were published before the setting was turned on won't have that benefit. This, unfortunately, includes un-publishing -- or switching to draft -- and then re-publishing old reviews. It's specific to the post object somewhere in the database and off the top of my head I don't know of an easy way to toggle it without maybe exporting all your reviews and re-importing them with the setting turned on (even then, it's possible -- as I haven't tested this, specifically -- that something in the post in the WordPress export file will still have the comments "off" toggle setting).

There is a _manual_ solution, which is, after toggling the setting in the Book Review Options, you can toggle "Allow Comments" in the Discussion box. The problem is you'll need to do it on a case-by-case basis, which is obnoxious and tedious. This can be sped up with tools like WP-CLI but that might be a bit ambitious to jump into (but if you're tech savvy, [definitely give it a look[(https://wp-cli.org/)).
